# Generated by Django 6.0.2 on 2026-02-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_rename_content_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
