# Generated by Django 6.0.2 on 2026-03-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_message_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='confidence_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
