# Generated by Django 6.0.2 on 2026-03-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_message_confidence_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
