# Generated by Django 6.0.2 on 2026-02-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='url',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='hell0', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
