# Generated by Django 6.0.2 on 2026-02-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_url_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.TextField(choices=[('policy', 'Policy'), ('faq', 'FAQ'), ('manual', 'Manual'), ('guide', 'Guide'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
